// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

/**
 * Protobuf type {@code blockchain.Block}
 */
public  final class Block extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.Block)
    BlockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Block.newBuilder() to construct.
  private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Block() {
    hashId_ = "";
    hash_ = "";
    previousHash_ = "";
    nonce_ = 0;
    timestamp_ = 0L;
    publicKey_ = "";
    nodeId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Block(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hashId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            hash_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            previousHash_ = s;
            break;
          }
          case 34: {
            group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder subBuilder = null;
            if (transactionsList_ != null) {
              subBuilder = transactionsList_.toBuilder();
            }
            transactionsList_ = input.readMessage(group3.ssd.blockchain.p2p.grpc.TransactionsList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transactionsList_);
              transactionsList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            nonce_ = input.readInt32();
            break;
          }
          case 48: {

            timestamp_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            publicKey_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_Block_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_Block_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            group3.ssd.blockchain.p2p.grpc.Block.class, group3.ssd.blockchain.p2p.grpc.Block.Builder.class);
  }

  public static final int HASHID_FIELD_NUMBER = 1;
  private volatile java.lang.Object hashId_;
  /**
   * <code>string hashId = 1;</code>
   */
  public java.lang.String getHashId() {
    java.lang.Object ref = hashId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hashId_ = s;
      return s;
    }
  }
  /**
   * <code>string hashId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHashIdBytes() {
    java.lang.Object ref = hashId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hashId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASH_FIELD_NUMBER = 2;
  private volatile java.lang.Object hash_;
  /**
   * <code>string hash = 2;</code>
   */
  public java.lang.String getHash() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hash_ = s;
      return s;
    }
  }
  /**
   * <code>string hash = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHashBytes() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREVIOUSHASH_FIELD_NUMBER = 3;
  private volatile java.lang.Object previousHash_;
  /**
   * <code>string previousHash = 3;</code>
   */
  public java.lang.String getPreviousHash() {
    java.lang.Object ref = previousHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      previousHash_ = s;
      return s;
    }
  }
  /**
   * <code>string previousHash = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPreviousHashBytes() {
    java.lang.Object ref = previousHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      previousHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONSLIST_FIELD_NUMBER = 4;
  private group3.ssd.blockchain.p2p.grpc.TransactionsList transactionsList_;
  /**
   * <code>.blockchain.TransactionsList transactionsList = 4;</code>
   */
  public boolean hasTransactionsList() {
    return transactionsList_ != null;
  }
  /**
   * <code>.blockchain.TransactionsList transactionsList = 4;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.TransactionsList getTransactionsList() {
    return transactionsList_ == null ? group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : transactionsList_;
  }
  /**
   * <code>.blockchain.TransactionsList transactionsList = 4;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder getTransactionsListOrBuilder() {
    return getTransactionsList();
  }

  public static final int NONCE_FIELD_NUMBER = 5;
  private int nonce_;
  /**
   * <code>int32 nonce = 5;</code>
   */
  public int getNonce() {
    return nonce_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 6;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int PUBLICKEY_FIELD_NUMBER = 7;
  private volatile java.lang.Object publicKey_;
  /**
   * <code>string publicKey = 7;</code>
   */
  public java.lang.String getPublicKey() {
    java.lang.Object ref = publicKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      publicKey_ = s;
      return s;
    }
  }
  /**
   * <code>string publicKey = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPublicKeyBytes() {
    java.lang.Object ref = publicKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publicKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODEID_FIELD_NUMBER = 8;
  private volatile java.lang.Object nodeId_;
  /**
   * <code>string nodeId = 8;</code>
   */
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string nodeId = 8;</code>
   */
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHashIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hashId_);
    }
    if (!getHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hash_);
    }
    if (!getPreviousHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, previousHash_);
    }
    if (transactionsList_ != null) {
      output.writeMessage(4, getTransactionsList());
    }
    if (nonce_ != 0) {
      output.writeInt32(5, nonce_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (!getPublicKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, publicKey_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nodeId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHashIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hashId_);
    }
    if (!getHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hash_);
    }
    if (!getPreviousHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, previousHash_);
    }
    if (transactionsList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTransactionsList());
    }
    if (nonce_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, nonce_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (!getPublicKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, publicKey_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nodeId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof group3.ssd.blockchain.p2p.grpc.Block)) {
      return super.equals(obj);
    }
    group3.ssd.blockchain.p2p.grpc.Block other = (group3.ssd.blockchain.p2p.grpc.Block) obj;

    boolean result = true;
    result = result && getHashId()
        .equals(other.getHashId());
    result = result && getHash()
        .equals(other.getHash());
    result = result && getPreviousHash()
        .equals(other.getPreviousHash());
    result = result && (hasTransactionsList() == other.hasTransactionsList());
    if (hasTransactionsList()) {
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
    }
    result = result && (getNonce()
        == other.getNonce());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && getPublicKey()
        .equals(other.getPublicKey());
    result = result && getNodeId()
        .equals(other.getNodeId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASHID_FIELD_NUMBER;
    hash = (53 * hash) + getHashId().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + PREVIOUSHASH_FIELD_NUMBER;
    hash = (53 * hash) + getPreviousHash().hashCode();
    if (hasTransactionsList()) {
      hash = (37 * hash) + TRANSACTIONSLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.Block parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(group3.ssd.blockchain.p2p.grpc.Block prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.Block}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.Block)
      group3.ssd.blockchain.p2p.grpc.BlockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_Block_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group3.ssd.blockchain.p2p.grpc.Block.class, group3.ssd.blockchain.p2p.grpc.Block.Builder.class);
    }

    // Construct using group3.ssd.blockchain.p2p.grpc.Block.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hashId_ = "";

      hash_ = "";

      previousHash_ = "";

      if (transactionsListBuilder_ == null) {
        transactionsList_ = null;
      } else {
        transactionsList_ = null;
        transactionsListBuilder_ = null;
      }
      nonce_ = 0;

      timestamp_ = 0L;

      publicKey_ = "";

      nodeId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_Block_descriptor;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.Block getDefaultInstanceForType() {
      return group3.ssd.blockchain.p2p.grpc.Block.getDefaultInstance();
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.Block build() {
      group3.ssd.blockchain.p2p.grpc.Block result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.Block buildPartial() {
      group3.ssd.blockchain.p2p.grpc.Block result = new group3.ssd.blockchain.p2p.grpc.Block(this);
      result.hashId_ = hashId_;
      result.hash_ = hash_;
      result.previousHash_ = previousHash_;
      if (transactionsListBuilder_ == null) {
        result.transactionsList_ = transactionsList_;
      } else {
        result.transactionsList_ = transactionsListBuilder_.build();
      }
      result.nonce_ = nonce_;
      result.timestamp_ = timestamp_;
      result.publicKey_ = publicKey_;
      result.nodeId_ = nodeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof group3.ssd.blockchain.p2p.grpc.Block) {
        return mergeFrom((group3.ssd.blockchain.p2p.grpc.Block)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(group3.ssd.blockchain.p2p.grpc.Block other) {
      if (other == group3.ssd.blockchain.p2p.grpc.Block.getDefaultInstance()) return this;
      if (!other.getHashId().isEmpty()) {
        hashId_ = other.hashId_;
        onChanged();
      }
      if (!other.getHash().isEmpty()) {
        hash_ = other.hash_;
        onChanged();
      }
      if (!other.getPreviousHash().isEmpty()) {
        previousHash_ = other.previousHash_;
        onChanged();
      }
      if (other.hasTransactionsList()) {
        mergeTransactionsList(other.getTransactionsList());
      }
      if (other.getNonce() != 0) {
        setNonce(other.getNonce());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getPublicKey().isEmpty()) {
        publicKey_ = other.publicKey_;
        onChanged();
      }
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      group3.ssd.blockchain.p2p.grpc.Block parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (group3.ssd.blockchain.p2p.grpc.Block) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hashId_ = "";
    /**
     * <code>string hashId = 1;</code>
     */
    public java.lang.String getHashId() {
      java.lang.Object ref = hashId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hashId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHashIdBytes() {
      java.lang.Object ref = hashId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hashId = 1;</code>
     */
    public Builder setHashId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hashId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hashId = 1;</code>
     */
    public Builder clearHashId() {
      
      hashId_ = getDefaultInstance().getHashId();
      onChanged();
      return this;
    }
    /**
     * <code>string hashId = 1;</code>
     */
    public Builder setHashIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hashId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hash_ = "";
    /**
     * <code>string hash = 2;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hash = 2;</code>
     */
    public Builder setHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 2;</code>
     */
    public Builder clearHash() {
      
      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 2;</code>
     */
    public Builder setHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hash_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object previousHash_ = "";
    /**
     * <code>string previousHash = 3;</code>
     */
    public java.lang.String getPreviousHash() {
      java.lang.Object ref = previousHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        previousHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string previousHash = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPreviousHashBytes() {
      java.lang.Object ref = previousHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        previousHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string previousHash = 3;</code>
     */
    public Builder setPreviousHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      previousHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string previousHash = 3;</code>
     */
    public Builder clearPreviousHash() {
      
      previousHash_ = getDefaultInstance().getPreviousHash();
      onChanged();
      return this;
    }
    /**
     * <code>string previousHash = 3;</code>
     */
    public Builder setPreviousHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      previousHash_ = value;
      onChanged();
      return this;
    }

    private group3.ssd.blockchain.p2p.grpc.TransactionsList transactionsList_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder> transactionsListBuilder_;
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public boolean hasTransactionsList() {
      return transactionsListBuilder_ != null || transactionsList_ != null;
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsList getTransactionsList() {
      if (transactionsListBuilder_ == null) {
        return transactionsList_ == null ? group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : transactionsList_;
      } else {
        return transactionsListBuilder_.getMessage();
      }
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public Builder setTransactionsList(group3.ssd.blockchain.p2p.grpc.TransactionsList value) {
      if (transactionsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transactionsList_ = value;
        onChanged();
      } else {
        transactionsListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public Builder setTransactionsList(
        group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder builderForValue) {
      if (transactionsListBuilder_ == null) {
        transactionsList_ = builderForValue.build();
        onChanged();
      } else {
        transactionsListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public Builder mergeTransactionsList(group3.ssd.blockchain.p2p.grpc.TransactionsList value) {
      if (transactionsListBuilder_ == null) {
        if (transactionsList_ != null) {
          transactionsList_ =
            group3.ssd.blockchain.p2p.grpc.TransactionsList.newBuilder(transactionsList_).mergeFrom(value).buildPartial();
        } else {
          transactionsList_ = value;
        }
        onChanged();
      } else {
        transactionsListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public Builder clearTransactionsList() {
      if (transactionsListBuilder_ == null) {
        transactionsList_ = null;
        onChanged();
      } else {
        transactionsList_ = null;
        transactionsListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder getTransactionsListBuilder() {
      
      onChanged();
      return getTransactionsListFieldBuilder().getBuilder();
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder getTransactionsListOrBuilder() {
      if (transactionsListBuilder_ != null) {
        return transactionsListBuilder_.getMessageOrBuilder();
      } else {
        return transactionsList_ == null ?
            group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : transactionsList_;
      }
    }
    /**
     * <code>.blockchain.TransactionsList transactionsList = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder> 
        getTransactionsListFieldBuilder() {
      if (transactionsListBuilder_ == null) {
        transactionsListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder>(
                getTransactionsList(),
                getParentForChildren(),
                isClean());
        transactionsList_ = null;
      }
      return transactionsListBuilder_;
    }

    private int nonce_ ;
    /**
     * <code>int32 nonce = 5;</code>
     */
    public int getNonce() {
      return nonce_;
    }
    /**
     * <code>int32 nonce = 5;</code>
     */
    public Builder setNonce(int value) {
      
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nonce = 5;</code>
     */
    public Builder clearNonce() {
      
      nonce_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object publicKey_ = "";
    /**
     * <code>string publicKey = 7;</code>
     */
    public java.lang.String getPublicKey() {
      java.lang.Object ref = publicKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string publicKey = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPublicKeyBytes() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string publicKey = 7;</code>
     */
    public Builder setPublicKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string publicKey = 7;</code>
     */
    public Builder clearPublicKey() {
      
      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }
    /**
     * <code>string publicKey = 7;</code>
     */
    public Builder setPublicKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      publicKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 8;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nodeId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nodeId = 8;</code>
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nodeId = 8;</code>
     */
    public Builder clearNodeId() {
      
      nodeId_ = getDefaultInstance().getNodeId();
      onChanged();
      return this;
    }
    /**
     * <code>string nodeId = 8;</code>
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.Block)
  }

  // @@protoc_insertion_point(class_scope:blockchain.Block)
  private static final group3.ssd.blockchain.p2p.grpc.Block DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new group3.ssd.blockchain.p2p.grpc.Block();
  }

  public static group3.ssd.blockchain.p2p.grpc.Block getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Block>
      PARSER = new com.google.protobuf.AbstractParser<Block>() {
    @java.lang.Override
    public Block parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Block(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Block> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Block> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public group3.ssd.blockchain.p2p.grpc.Block getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

