// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

/**
 * Protobuf type {@code blockchain.BlockChain}
 */
public  final class BlockChain extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.BlockChain)
    BlockChainOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockChain.newBuilder() to construct.
  private BlockChain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockChain() {
    chain_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlockChain(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              chain_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Block>();
              mutable_bitField0_ |= 0x00000001;
            }
            chain_.add(
                input.readMessage(group3.ssd.blockchain.p2p.grpc.Block.parser(), extensionRegistry));
            break;
          }
          case 18: {
            group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder subBuilder = null;
            if (pendingTransactions_ != null) {
              subBuilder = pendingTransactions_.toBuilder();
            }
            pendingTransactions_ = input.readMessage(group3.ssd.blockchain.p2p.grpc.TransactionsList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pendingTransactions_);
              pendingTransactions_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        chain_ = java.util.Collections.unmodifiableList(chain_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_BlockChain_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_BlockChain_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            group3.ssd.blockchain.p2p.grpc.BlockChain.class, group3.ssd.blockchain.p2p.grpc.BlockChain.Builder.class);
  }

  private int bitField0_;
  public static final int CHAIN_FIELD_NUMBER = 1;
  private java.util.List<group3.ssd.blockchain.p2p.grpc.Block> chain_;
  /**
   * <code>repeated .blockchain.Block chain = 1;</code>
   */
  public java.util.List<group3.ssd.blockchain.p2p.grpc.Block> getChainList() {
    return chain_;
  }
  /**
   * <code>repeated .blockchain.Block chain = 1;</code>
   */
  public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.BlockOrBuilder> 
      getChainOrBuilderList() {
    return chain_;
  }
  /**
   * <code>repeated .blockchain.Block chain = 1;</code>
   */
  public int getChainCount() {
    return chain_.size();
  }
  /**
   * <code>repeated .blockchain.Block chain = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.Block getChain(int index) {
    return chain_.get(index);
  }
  /**
   * <code>repeated .blockchain.Block chain = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.BlockOrBuilder getChainOrBuilder(
      int index) {
    return chain_.get(index);
  }

  public static final int PENDINGTRANSACTIONS_FIELD_NUMBER = 2;
  private group3.ssd.blockchain.p2p.grpc.TransactionsList pendingTransactions_;
  /**
   * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
   */
  public boolean hasPendingTransactions() {
    return pendingTransactions_ != null;
  }
  /**
   * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.TransactionsList getPendingTransactions() {
    return pendingTransactions_ == null ? group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : pendingTransactions_;
  }
  /**
   * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder getPendingTransactionsOrBuilder() {
    return getPendingTransactions();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chain_.size(); i++) {
      output.writeMessage(1, chain_.get(i));
    }
    if (pendingTransactions_ != null) {
      output.writeMessage(2, getPendingTransactions());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chain_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chain_.get(i));
    }
    if (pendingTransactions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPendingTransactions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof group3.ssd.blockchain.p2p.grpc.BlockChain)) {
      return super.equals(obj);
    }
    group3.ssd.blockchain.p2p.grpc.BlockChain other = (group3.ssd.blockchain.p2p.grpc.BlockChain) obj;

    boolean result = true;
    result = result && getChainList()
        .equals(other.getChainList());
    result = result && (hasPendingTransactions() == other.hasPendingTransactions());
    if (hasPendingTransactions()) {
      result = result && getPendingTransactions()
          .equals(other.getPendingTransactions());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChainCount() > 0) {
      hash = (37 * hash) + CHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getChainList().hashCode();
    }
    if (hasPendingTransactions()) {
      hash = (37 * hash) + PENDINGTRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPendingTransactions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.BlockChain parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(group3.ssd.blockchain.p2p.grpc.BlockChain prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.BlockChain}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.BlockChain)
      group3.ssd.blockchain.p2p.grpc.BlockChainOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_BlockChain_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_BlockChain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group3.ssd.blockchain.p2p.grpc.BlockChain.class, group3.ssd.blockchain.p2p.grpc.BlockChain.Builder.class);
    }

    // Construct using group3.ssd.blockchain.p2p.grpc.BlockChain.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChainFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (chainBuilder_ == null) {
        chain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        chainBuilder_.clear();
      }
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactions_ = null;
      } else {
        pendingTransactions_ = null;
        pendingTransactionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_BlockChain_descriptor;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.BlockChain getDefaultInstanceForType() {
      return group3.ssd.blockchain.p2p.grpc.BlockChain.getDefaultInstance();
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.BlockChain build() {
      group3.ssd.blockchain.p2p.grpc.BlockChain result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.BlockChain buildPartial() {
      group3.ssd.blockchain.p2p.grpc.BlockChain result = new group3.ssd.blockchain.p2p.grpc.BlockChain(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (chainBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          chain_ = java.util.Collections.unmodifiableList(chain_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chain_ = chain_;
      } else {
        result.chain_ = chainBuilder_.build();
      }
      if (pendingTransactionsBuilder_ == null) {
        result.pendingTransactions_ = pendingTransactions_;
      } else {
        result.pendingTransactions_ = pendingTransactionsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof group3.ssd.blockchain.p2p.grpc.BlockChain) {
        return mergeFrom((group3.ssd.blockchain.p2p.grpc.BlockChain)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(group3.ssd.blockchain.p2p.grpc.BlockChain other) {
      if (other == group3.ssd.blockchain.p2p.grpc.BlockChain.getDefaultInstance()) return this;
      if (chainBuilder_ == null) {
        if (!other.chain_.isEmpty()) {
          if (chain_.isEmpty()) {
            chain_ = other.chain_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChainIsMutable();
            chain_.addAll(other.chain_);
          }
          onChanged();
        }
      } else {
        if (!other.chain_.isEmpty()) {
          if (chainBuilder_.isEmpty()) {
            chainBuilder_.dispose();
            chainBuilder_ = null;
            chain_ = other.chain_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chainBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChainFieldBuilder() : null;
          } else {
            chainBuilder_.addAllMessages(other.chain_);
          }
        }
      }
      if (other.hasPendingTransactions()) {
        mergePendingTransactions(other.getPendingTransactions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      group3.ssd.blockchain.p2p.grpc.BlockChain parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (group3.ssd.blockchain.p2p.grpc.BlockChain) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<group3.ssd.blockchain.p2p.grpc.Block> chain_ =
      java.util.Collections.emptyList();
    private void ensureChainIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        chain_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Block>(chain_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Block, group3.ssd.blockchain.p2p.grpc.Block.Builder, group3.ssd.blockchain.p2p.grpc.BlockOrBuilder> chainBuilder_;

    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Block> getChainList() {
      if (chainBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chain_);
      } else {
        return chainBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public int getChainCount() {
      if (chainBuilder_ == null) {
        return chain_.size();
      } else {
        return chainBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Block getChain(int index) {
      if (chainBuilder_ == null) {
        return chain_.get(index);
      } else {
        return chainBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder setChain(
        int index, group3.ssd.blockchain.p2p.grpc.Block value) {
      if (chainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChainIsMutable();
        chain_.set(index, value);
        onChanged();
      } else {
        chainBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder setChain(
        int index, group3.ssd.blockchain.p2p.grpc.Block.Builder builderForValue) {
      if (chainBuilder_ == null) {
        ensureChainIsMutable();
        chain_.set(index, builderForValue.build());
        onChanged();
      } else {
        chainBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder addChain(group3.ssd.blockchain.p2p.grpc.Block value) {
      if (chainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChainIsMutable();
        chain_.add(value);
        onChanged();
      } else {
        chainBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder addChain(
        int index, group3.ssd.blockchain.p2p.grpc.Block value) {
      if (chainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChainIsMutable();
        chain_.add(index, value);
        onChanged();
      } else {
        chainBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder addChain(
        group3.ssd.blockchain.p2p.grpc.Block.Builder builderForValue) {
      if (chainBuilder_ == null) {
        ensureChainIsMutable();
        chain_.add(builderForValue.build());
        onChanged();
      } else {
        chainBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder addChain(
        int index, group3.ssd.blockchain.p2p.grpc.Block.Builder builderForValue) {
      if (chainBuilder_ == null) {
        ensureChainIsMutable();
        chain_.add(index, builderForValue.build());
        onChanged();
      } else {
        chainBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder addAllChain(
        java.lang.Iterable<? extends group3.ssd.blockchain.p2p.grpc.Block> values) {
      if (chainBuilder_ == null) {
        ensureChainIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chain_);
        onChanged();
      } else {
        chainBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder clearChain() {
      if (chainBuilder_ == null) {
        chain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chainBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public Builder removeChain(int index) {
      if (chainBuilder_ == null) {
        ensureChainIsMutable();
        chain_.remove(index);
        onChanged();
      } else {
        chainBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Block.Builder getChainBuilder(
        int index) {
      return getChainFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.BlockOrBuilder getChainOrBuilder(
        int index) {
      if (chainBuilder_ == null) {
        return chain_.get(index);  } else {
        return chainBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.BlockOrBuilder> 
         getChainOrBuilderList() {
      if (chainBuilder_ != null) {
        return chainBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chain_);
      }
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Block.Builder addChainBuilder() {
      return getChainFieldBuilder().addBuilder(
          group3.ssd.blockchain.p2p.grpc.Block.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Block.Builder addChainBuilder(
        int index) {
      return getChainFieldBuilder().addBuilder(
          index, group3.ssd.blockchain.p2p.grpc.Block.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Block chain = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Block.Builder> 
         getChainBuilderList() {
      return getChainFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Block, group3.ssd.blockchain.p2p.grpc.Block.Builder, group3.ssd.blockchain.p2p.grpc.BlockOrBuilder> 
        getChainFieldBuilder() {
      if (chainBuilder_ == null) {
        chainBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            group3.ssd.blockchain.p2p.grpc.Block, group3.ssd.blockchain.p2p.grpc.Block.Builder, group3.ssd.blockchain.p2p.grpc.BlockOrBuilder>(
                chain_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        chain_ = null;
      }
      return chainBuilder_;
    }

    private group3.ssd.blockchain.p2p.grpc.TransactionsList pendingTransactions_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder> pendingTransactionsBuilder_;
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public boolean hasPendingTransactions() {
      return pendingTransactionsBuilder_ != null || pendingTransactions_ != null;
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsList getPendingTransactions() {
      if (pendingTransactionsBuilder_ == null) {
        return pendingTransactions_ == null ? group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : pendingTransactions_;
      } else {
        return pendingTransactionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public Builder setPendingTransactions(group3.ssd.blockchain.p2p.grpc.TransactionsList value) {
      if (pendingTransactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pendingTransactions_ = value;
        onChanged();
      } else {
        pendingTransactionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public Builder setPendingTransactions(
        group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder builderForValue) {
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactions_ = builderForValue.build();
        onChanged();
      } else {
        pendingTransactionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public Builder mergePendingTransactions(group3.ssd.blockchain.p2p.grpc.TransactionsList value) {
      if (pendingTransactionsBuilder_ == null) {
        if (pendingTransactions_ != null) {
          pendingTransactions_ =
            group3.ssd.blockchain.p2p.grpc.TransactionsList.newBuilder(pendingTransactions_).mergeFrom(value).buildPartial();
        } else {
          pendingTransactions_ = value;
        }
        onChanged();
      } else {
        pendingTransactionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public Builder clearPendingTransactions() {
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactions_ = null;
        onChanged();
      } else {
        pendingTransactions_ = null;
        pendingTransactionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder getPendingTransactionsBuilder() {
      
      onChanged();
      return getPendingTransactionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder getPendingTransactionsOrBuilder() {
      if (pendingTransactionsBuilder_ != null) {
        return pendingTransactionsBuilder_.getMessageOrBuilder();
      } else {
        return pendingTransactions_ == null ?
            group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance() : pendingTransactions_;
      }
    }
    /**
     * <code>.blockchain.TransactionsList pendingTransactions = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder> 
        getPendingTransactionsFieldBuilder() {
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            group3.ssd.blockchain.p2p.grpc.TransactionsList, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder, group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder>(
                getPendingTransactions(),
                getParentForChildren(),
                isClean());
        pendingTransactions_ = null;
      }
      return pendingTransactionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.BlockChain)
  }

  // @@protoc_insertion_point(class_scope:blockchain.BlockChain)
  private static final group3.ssd.blockchain.p2p.grpc.BlockChain DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new group3.ssd.blockchain.p2p.grpc.BlockChain();
  }

  public static group3.ssd.blockchain.p2p.grpc.BlockChain getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockChain>
      PARSER = new com.google.protobuf.AbstractParser<BlockChain>() {
    @java.lang.Override
    public BlockChain parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlockChain(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlockChain> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockChain> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public group3.ssd.blockchain.p2p.grpc.BlockChain getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

