// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

public interface IPAddresOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.IPAddres)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string port = 2;</code>
   */
  java.lang.String getPort();
  /**
   * <code>string port = 2;</code>
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
