// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

/**
 * Protobuf type {@code blockchain.KBucket_GRPC}
 */
public  final class KBucket_GRPC extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.KBucket_GRPC)
    KBucket_GRPCOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KBucket_GRPC.newBuilder() to construct.
  private KBucket_GRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KBucket_GRPC() {
    kbucket_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KBucket_GRPC(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              kbucket_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Node_GRPC>();
              mutable_bitField0_ |= 0x00000001;
            }
            kbucket_.add(
                input.readMessage(group3.ssd.blockchain.p2p.grpc.Node_GRPC.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        kbucket_ = java.util.Collections.unmodifiableList(kbucket_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_KBucket_GRPC_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_KBucket_GRPC_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.class, group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.Builder.class);
  }

  public static final int KBUCKET_FIELD_NUMBER = 1;
  private java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC> kbucket_;
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  public java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC> getKbucketList() {
    return kbucket_;
  }
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder> 
      getKbucketOrBuilderList() {
    return kbucket_;
  }
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  public int getKbucketCount() {
    return kbucket_.size();
  }
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.Node_GRPC getKbucket(int index) {
    return kbucket_.get(index);
  }
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder getKbucketOrBuilder(
      int index) {
    return kbucket_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < kbucket_.size(); i++) {
      output.writeMessage(1, kbucket_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < kbucket_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, kbucket_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof group3.ssd.blockchain.p2p.grpc.KBucket_GRPC)) {
      return super.equals(obj);
    }
    group3.ssd.blockchain.p2p.grpc.KBucket_GRPC other = (group3.ssd.blockchain.p2p.grpc.KBucket_GRPC) obj;

    boolean result = true;
    result = result && getKbucketList()
        .equals(other.getKbucketList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKbucketCount() > 0) {
      hash = (37 * hash) + KBUCKET_FIELD_NUMBER;
      hash = (53 * hash) + getKbucketList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(group3.ssd.blockchain.p2p.grpc.KBucket_GRPC prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.KBucket_GRPC}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.KBucket_GRPC)
      group3.ssd.blockchain.p2p.grpc.KBucket_GRPCOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_KBucket_GRPC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_KBucket_GRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.class, group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.Builder.class);
    }

    // Construct using group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKbucketFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (kbucketBuilder_ == null) {
        kbucket_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        kbucketBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_KBucket_GRPC_descriptor;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.KBucket_GRPC getDefaultInstanceForType() {
      return group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.getDefaultInstance();
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.KBucket_GRPC build() {
      group3.ssd.blockchain.p2p.grpc.KBucket_GRPC result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.KBucket_GRPC buildPartial() {
      group3.ssd.blockchain.p2p.grpc.KBucket_GRPC result = new group3.ssd.blockchain.p2p.grpc.KBucket_GRPC(this);
      int from_bitField0_ = bitField0_;
      if (kbucketBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          kbucket_ = java.util.Collections.unmodifiableList(kbucket_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.kbucket_ = kbucket_;
      } else {
        result.kbucket_ = kbucketBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof group3.ssd.blockchain.p2p.grpc.KBucket_GRPC) {
        return mergeFrom((group3.ssd.blockchain.p2p.grpc.KBucket_GRPC)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(group3.ssd.blockchain.p2p.grpc.KBucket_GRPC other) {
      if (other == group3.ssd.blockchain.p2p.grpc.KBucket_GRPC.getDefaultInstance()) return this;
      if (kbucketBuilder_ == null) {
        if (!other.kbucket_.isEmpty()) {
          if (kbucket_.isEmpty()) {
            kbucket_ = other.kbucket_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKbucketIsMutable();
            kbucket_.addAll(other.kbucket_);
          }
          onChanged();
        }
      } else {
        if (!other.kbucket_.isEmpty()) {
          if (kbucketBuilder_.isEmpty()) {
            kbucketBuilder_.dispose();
            kbucketBuilder_ = null;
            kbucket_ = other.kbucket_;
            bitField0_ = (bitField0_ & ~0x00000001);
            kbucketBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKbucketFieldBuilder() : null;
          } else {
            kbucketBuilder_.addAllMessages(other.kbucket_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      group3.ssd.blockchain.p2p.grpc.KBucket_GRPC parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (group3.ssd.blockchain.p2p.grpc.KBucket_GRPC) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC> kbucket_ =
      java.util.Collections.emptyList();
    private void ensureKbucketIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        kbucket_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Node_GRPC>(kbucket_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Node_GRPC, group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder, group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder> kbucketBuilder_;

    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC> getKbucketList() {
      if (kbucketBuilder_ == null) {
        return java.util.Collections.unmodifiableList(kbucket_);
      } else {
        return kbucketBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public int getKbucketCount() {
      if (kbucketBuilder_ == null) {
        return kbucket_.size();
      } else {
        return kbucketBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Node_GRPC getKbucket(int index) {
      if (kbucketBuilder_ == null) {
        return kbucket_.get(index);
      } else {
        return kbucketBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder setKbucket(
        int index, group3.ssd.blockchain.p2p.grpc.Node_GRPC value) {
      if (kbucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKbucketIsMutable();
        kbucket_.set(index, value);
        onChanged();
      } else {
        kbucketBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder setKbucket(
        int index, group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder builderForValue) {
      if (kbucketBuilder_ == null) {
        ensureKbucketIsMutable();
        kbucket_.set(index, builderForValue.build());
        onChanged();
      } else {
        kbucketBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder addKbucket(group3.ssd.blockchain.p2p.grpc.Node_GRPC value) {
      if (kbucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKbucketIsMutable();
        kbucket_.add(value);
        onChanged();
      } else {
        kbucketBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder addKbucket(
        int index, group3.ssd.blockchain.p2p.grpc.Node_GRPC value) {
      if (kbucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKbucketIsMutable();
        kbucket_.add(index, value);
        onChanged();
      } else {
        kbucketBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder addKbucket(
        group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder builderForValue) {
      if (kbucketBuilder_ == null) {
        ensureKbucketIsMutable();
        kbucket_.add(builderForValue.build());
        onChanged();
      } else {
        kbucketBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder addKbucket(
        int index, group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder builderForValue) {
      if (kbucketBuilder_ == null) {
        ensureKbucketIsMutable();
        kbucket_.add(index, builderForValue.build());
        onChanged();
      } else {
        kbucketBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder addAllKbucket(
        java.lang.Iterable<? extends group3.ssd.blockchain.p2p.grpc.Node_GRPC> values) {
      if (kbucketBuilder_ == null) {
        ensureKbucketIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kbucket_);
        onChanged();
      } else {
        kbucketBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder clearKbucket() {
      if (kbucketBuilder_ == null) {
        kbucket_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        kbucketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public Builder removeKbucket(int index) {
      if (kbucketBuilder_ == null) {
        ensureKbucketIsMutable();
        kbucket_.remove(index);
        onChanged();
      } else {
        kbucketBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder getKbucketBuilder(
        int index) {
      return getKbucketFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder getKbucketOrBuilder(
        int index) {
      if (kbucketBuilder_ == null) {
        return kbucket_.get(index);  } else {
        return kbucketBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder> 
         getKbucketOrBuilderList() {
      if (kbucketBuilder_ != null) {
        return kbucketBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(kbucket_);
      }
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder addKbucketBuilder() {
      return getKbucketFieldBuilder().addBuilder(
          group3.ssd.blockchain.p2p.grpc.Node_GRPC.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder addKbucketBuilder(
        int index) {
      return getKbucketFieldBuilder().addBuilder(
          index, group3.ssd.blockchain.p2p.grpc.Node_GRPC.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder> 
         getKbucketBuilderList() {
      return getKbucketFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Node_GRPC, group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder, group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder> 
        getKbucketFieldBuilder() {
      if (kbucketBuilder_ == null) {
        kbucketBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            group3.ssd.blockchain.p2p.grpc.Node_GRPC, group3.ssd.blockchain.p2p.grpc.Node_GRPC.Builder, group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder>(
                kbucket_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        kbucket_ = null;
      }
      return kbucketBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.KBucket_GRPC)
  }

  // @@protoc_insertion_point(class_scope:blockchain.KBucket_GRPC)
  private static final group3.ssd.blockchain.p2p.grpc.KBucket_GRPC DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new group3.ssd.blockchain.p2p.grpc.KBucket_GRPC();
  }

  public static group3.ssd.blockchain.p2p.grpc.KBucket_GRPC getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KBucket_GRPC>
      PARSER = new com.google.protobuf.AbstractParser<KBucket_GRPC>() {
    @java.lang.Override
    public KBucket_GRPC parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KBucket_GRPC(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KBucket_GRPC> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KBucket_GRPC> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public group3.ssd.blockchain.p2p.grpc.KBucket_GRPC getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

