// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

public interface KBucket_GRPCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.KBucket_GRPC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  java.util.List<group3.ssd.blockchain.p2p.grpc.Node_GRPC> 
      getKbucketList();
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  group3.ssd.blockchain.p2p.grpc.Node_GRPC getKbucket(int index);
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  int getKbucketCount();
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  java.util.List<? extends group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder> 
      getKbucketOrBuilderList();
  /**
   * <code>repeated .blockchain.Node_GRPC kbucket = 1;</code>
   */
  group3.ssd.blockchain.p2p.grpc.Node_GRPCOrBuilder getKbucketOrBuilder(
      int index);
}
