// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.Pong)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool pong = 1;</code>
   */
  boolean getPong();

  /**
   * <code>.blockchain.BlockChain blockchain = 2;</code>
   */
  boolean hasBlockchain();
  /**
   * <code>.blockchain.BlockChain blockchain = 2;</code>
   */
  group3.ssd.blockchain.p2p.grpc.BlockChain getBlockchain();
  /**
   * <code>.blockchain.BlockChain blockchain = 2;</code>
   */
  group3.ssd.blockchain.p2p.grpc.BlockChainOrBuilder getBlockchainOrBuilder();
}
