// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

/**
 * Protobuf type {@code blockchain.TransactionsList}
 */
public  final class TransactionsList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.TransactionsList)
    TransactionsListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionsList.newBuilder() to construct.
  private TransactionsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionsList() {
    transactionList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionsList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              transactionList_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Transaction>();
              mutable_bitField0_ |= 0x00000001;
            }
            transactionList_.add(
                input.readMessage(group3.ssd.blockchain.p2p.grpc.Transaction.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        transactionList_ = java.util.Collections.unmodifiableList(transactionList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_TransactionsList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_TransactionsList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            group3.ssd.blockchain.p2p.grpc.TransactionsList.class, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder.class);
  }

  public static final int TRANSACTIONLIST_FIELD_NUMBER = 1;
  private java.util.List<group3.ssd.blockchain.p2p.grpc.Transaction> transactionList_;
  /**
   * <code>repeated .blockchain.Transaction transactionList = 1;</code>
   */
  public java.util.List<group3.ssd.blockchain.p2p.grpc.Transaction> getTransactionListList() {
    return transactionList_;
  }
  /**
   * <code>repeated .blockchain.Transaction transactionList = 1;</code>
   */
  public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder> 
      getTransactionListOrBuilderList() {
    return transactionList_;
  }
  /**
   * <code>repeated .blockchain.Transaction transactionList = 1;</code>
   */
  public int getTransactionListCount() {
    return transactionList_.size();
  }
  /**
   * <code>repeated .blockchain.Transaction transactionList = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.Transaction getTransactionList(int index) {
    return transactionList_.get(index);
  }
  /**
   * <code>repeated .blockchain.Transaction transactionList = 1;</code>
   */
  public group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder getTransactionListOrBuilder(
      int index) {
    return transactionList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < transactionList_.size(); i++) {
      output.writeMessage(1, transactionList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < transactionList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, transactionList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof group3.ssd.blockchain.p2p.grpc.TransactionsList)) {
      return super.equals(obj);
    }
    group3.ssd.blockchain.p2p.grpc.TransactionsList other = (group3.ssd.blockchain.p2p.grpc.TransactionsList) obj;

    boolean result = true;
    result = result && getTransactionListList()
        .equals(other.getTransactionListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTransactionListCount() > 0) {
      hash = (37 * hash) + TRANSACTIONLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static group3.ssd.blockchain.p2p.grpc.TransactionsList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(group3.ssd.blockchain.p2p.grpc.TransactionsList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.TransactionsList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.TransactionsList)
      group3.ssd.blockchain.p2p.grpc.TransactionsListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_TransactionsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_TransactionsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group3.ssd.blockchain.p2p.grpc.TransactionsList.class, group3.ssd.blockchain.p2p.grpc.TransactionsList.Builder.class);
    }

    // Construct using group3.ssd.blockchain.p2p.grpc.TransactionsList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionListBuilder_ == null) {
        transactionList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transactionListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return group3.ssd.blockchain.p2p.grpc.BlockchainGRPCProto.internal_static_blockchain_TransactionsList_descriptor;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.TransactionsList getDefaultInstanceForType() {
      return group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance();
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.TransactionsList build() {
      group3.ssd.blockchain.p2p.grpc.TransactionsList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public group3.ssd.blockchain.p2p.grpc.TransactionsList buildPartial() {
      group3.ssd.blockchain.p2p.grpc.TransactionsList result = new group3.ssd.blockchain.p2p.grpc.TransactionsList(this);
      int from_bitField0_ = bitField0_;
      if (transactionListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          transactionList_ = java.util.Collections.unmodifiableList(transactionList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactionList_ = transactionList_;
      } else {
        result.transactionList_ = transactionListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof group3.ssd.blockchain.p2p.grpc.TransactionsList) {
        return mergeFrom((group3.ssd.blockchain.p2p.grpc.TransactionsList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(group3.ssd.blockchain.p2p.grpc.TransactionsList other) {
      if (other == group3.ssd.blockchain.p2p.grpc.TransactionsList.getDefaultInstance()) return this;
      if (transactionListBuilder_ == null) {
        if (!other.transactionList_.isEmpty()) {
          if (transactionList_.isEmpty()) {
            transactionList_ = other.transactionList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionListIsMutable();
            transactionList_.addAll(other.transactionList_);
          }
          onChanged();
        }
      } else {
        if (!other.transactionList_.isEmpty()) {
          if (transactionListBuilder_.isEmpty()) {
            transactionListBuilder_.dispose();
            transactionListBuilder_ = null;
            transactionList_ = other.transactionList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionListFieldBuilder() : null;
          } else {
            transactionListBuilder_.addAllMessages(other.transactionList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      group3.ssd.blockchain.p2p.grpc.TransactionsList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (group3.ssd.blockchain.p2p.grpc.TransactionsList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<group3.ssd.blockchain.p2p.grpc.Transaction> transactionList_ =
      java.util.Collections.emptyList();
    private void ensureTransactionListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        transactionList_ = new java.util.ArrayList<group3.ssd.blockchain.p2p.grpc.Transaction>(transactionList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Transaction, group3.ssd.blockchain.p2p.grpc.Transaction.Builder, group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder> transactionListBuilder_;

    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Transaction> getTransactionListList() {
      if (transactionListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactionList_);
      } else {
        return transactionListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public int getTransactionListCount() {
      if (transactionListBuilder_ == null) {
        return transactionList_.size();
      } else {
        return transactionListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Transaction getTransactionList(int index) {
      if (transactionListBuilder_ == null) {
        return transactionList_.get(index);
      } else {
        return transactionListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder setTransactionList(
        int index, group3.ssd.blockchain.p2p.grpc.Transaction value) {
      if (transactionListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionListIsMutable();
        transactionList_.set(index, value);
        onChanged();
      } else {
        transactionListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder setTransactionList(
        int index, group3.ssd.blockchain.p2p.grpc.Transaction.Builder builderForValue) {
      if (transactionListBuilder_ == null) {
        ensureTransactionListIsMutable();
        transactionList_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder addTransactionList(group3.ssd.blockchain.p2p.grpc.Transaction value) {
      if (transactionListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionListIsMutable();
        transactionList_.add(value);
        onChanged();
      } else {
        transactionListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder addTransactionList(
        int index, group3.ssd.blockchain.p2p.grpc.Transaction value) {
      if (transactionListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionListIsMutable();
        transactionList_.add(index, value);
        onChanged();
      } else {
        transactionListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder addTransactionList(
        group3.ssd.blockchain.p2p.grpc.Transaction.Builder builderForValue) {
      if (transactionListBuilder_ == null) {
        ensureTransactionListIsMutable();
        transactionList_.add(builderForValue.build());
        onChanged();
      } else {
        transactionListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder addTransactionList(
        int index, group3.ssd.blockchain.p2p.grpc.Transaction.Builder builderForValue) {
      if (transactionListBuilder_ == null) {
        ensureTransactionListIsMutable();
        transactionList_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder addAllTransactionList(
        java.lang.Iterable<? extends group3.ssd.blockchain.p2p.grpc.Transaction> values) {
      if (transactionListBuilder_ == null) {
        ensureTransactionListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionList_);
        onChanged();
      } else {
        transactionListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder clearTransactionList() {
      if (transactionListBuilder_ == null) {
        transactionList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public Builder removeTransactionList(int index) {
      if (transactionListBuilder_ == null) {
        ensureTransactionListIsMutable();
        transactionList_.remove(index);
        onChanged();
      } else {
        transactionListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Transaction.Builder getTransactionListBuilder(
        int index) {
      return getTransactionListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder getTransactionListOrBuilder(
        int index) {
      if (transactionListBuilder_ == null) {
        return transactionList_.get(index);  } else {
        return transactionListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public java.util.List<? extends group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder> 
         getTransactionListOrBuilderList() {
      if (transactionListBuilder_ != null) {
        return transactionListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactionList_);
      }
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Transaction.Builder addTransactionListBuilder() {
      return getTransactionListFieldBuilder().addBuilder(
          group3.ssd.blockchain.p2p.grpc.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public group3.ssd.blockchain.p2p.grpc.Transaction.Builder addTransactionListBuilder(
        int index) {
      return getTransactionListFieldBuilder().addBuilder(
          index, group3.ssd.blockchain.p2p.grpc.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .blockchain.Transaction transactionList = 1;</code>
     */
    public java.util.List<group3.ssd.blockchain.p2p.grpc.Transaction.Builder> 
         getTransactionListBuilderList() {
      return getTransactionListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        group3.ssd.blockchain.p2p.grpc.Transaction, group3.ssd.blockchain.p2p.grpc.Transaction.Builder, group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder> 
        getTransactionListFieldBuilder() {
      if (transactionListBuilder_ == null) {
        transactionListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            group3.ssd.blockchain.p2p.grpc.Transaction, group3.ssd.blockchain.p2p.grpc.Transaction.Builder, group3.ssd.blockchain.p2p.grpc.TransactionOrBuilder>(
                transactionList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        transactionList_ = null;
      }
      return transactionListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.TransactionsList)
  }

  // @@protoc_insertion_point(class_scope:blockchain.TransactionsList)
  private static final group3.ssd.blockchain.p2p.grpc.TransactionsList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new group3.ssd.blockchain.p2p.grpc.TransactionsList();
  }

  public static group3.ssd.blockchain.p2p.grpc.TransactionsList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionsList>
      PARSER = new com.google.protobuf.AbstractParser<TransactionsList>() {
    @java.lang.Override
    public TransactionsList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionsList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionsList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionsList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public group3.ssd.blockchain.p2p.grpc.TransactionsList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

