// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package group3.ssd.blockchain.p2p.grpc;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hash = 1;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 1;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();

  /**
   * <code>string senderPK = 2;</code>
   */
  java.lang.String getSenderPK();
  /**
   * <code>string senderPK = 2;</code>
   */
  com.google.protobuf.ByteString
      getSenderPKBytes();

  /**
   * <code>string receiverPK = 3;</code>
   */
  java.lang.String getReceiverPK();
  /**
   * <code>string receiverPK = 3;</code>
   */
  com.google.protobuf.ByteString
      getReceiverPKBytes();

  /**
   * <code>bytes signature = 4;</code>
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>int64 timestamp = 5;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 amount = 6;</code>
   */
  int getAmount();

  /**
   * <code>string misc = 7;</code>
   */
  java.lang.String getMisc();
  /**
   * <code>string misc = 7;</code>
   */
  com.google.protobuf.ByteString
      getMiscBytes();

  /**
   * <code>string nodeId = 8;</code>
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 8;</code>
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
